# Generated by Django 5.0.6 on 2024-08-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_like_workoutlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='like',
        ),
    ]
