# Generated by Django 5.0.6 on 2024-08-14 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_remove_workout_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutcomment',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workout.workout'),
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workout.workout'),
        ),
        migrations.AlterField(
            model_name='workoutlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
